name: "Feature Request"
description: "Suggest a new feature or improvement"
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "## Feature Request\nDescribe the feature or improvement you'd like to see."
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this feature would be useful."
  - type: textarea
    id: proposal
    attributes:
      label: "Proposed Solution (Optional)"
      description: "Describe how this feature could be implemented."
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context related to the feature."
